chore: CIワークフローの結果チェックを強化 (#47)
- CIワークフローの成功条件を変更し、すべての依存ジョブが成功またはスキップされた場合のみ成功と見なすように修正しました。
- 成功しなかった場合のエラーメッセージを追加し、適切な終了コードを返すようにしました。

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -293,8 +293,24 @@ jobs:
     needs:
       - lint-and-test
       - security-scan
-    if: ${{ !failure() }}
+    if: ${{ always() }}
     runs-on: ubuntu-latest
 
     steps:
-      - run: echo "Success!!"
+      - name: Check job result
+        run: |
+          RESULT="${{ needs.lint-and-test.result }}"
+
+          if [[ $RESULT != "success" && $RESULT != "skipped" ]]; then
+            echo "This workflow failed or was cancelled!"
+            exit 1
+          fi
+
+          RESULT="${{ needs.security-scan.result }}"
+          if [[ $RESULT != "success" && $RESULT != "skipped" ]]; then
+            echo "This workflow failed or was cancelled!"
+            exit 1
+          fi
+
+          echo "Success!!"
+          exit 0
